include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # Use pub dependencies sorting from Pubspec Assist VSCode extension instead
    sort_pub_dependencies: false
